# Generated by Django 4.2.1 on 2023-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
